spring:
  application:
    name: MediaService

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    # Limite de archivo (fotos)
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


server:
  port: 9093

media:
  storage:
    location: ${MEDIA_STORAGE_LOCATION:./uploads}

logging:
  file:
    name: logs/media.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7